#!/usr/bin/env node
// Writes the coverage statement the explorer shows (web/src/lib/release-coverage.json) from the one route coverage table
// (coverage.ts), the merged registry and the public catalogue. The explorer adds what the STORE really holds at read
// time, from the database: this file says which routes exist, never that anything has been loaded.
//
//   node src/loaders/coverage_build.ts            check: exit 1 when the committed file is out of date
//   node src/loaders/coverage_build.ts --write

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { SourcesFile } from "../../../supabase/functions/_shared/types.ts";
import sourcesFile from "../../../supabase/functions/_shared/sources.config.json" with { type: "json" };
import { REPOSITORY_ROOT } from "./access.ts";
import { productCoverage, type RouteState, UNPUBLISHED_2026 } from "./coverage.ts";
import { mergeRegistry } from "./registry.ts";

const TARGET = resolve(REPOSITORY_ROOT, "web/src/lib/release-coverage.json");

/** How a product is kept current, in the order of preference a reader cares about. */
export type RefreshKind = "scheduled" | "operator_run" | "exercised_only" | "pending_decision" | "none";

const RUNNABLE: ReadonlySet<RouteState> = new Set(["working", "working_cli_only", "exercised_not_run_in_full"]);

export async function buildCoverageFile(): Promise<string> {
  const { file, problems } = mergeRegistry(sourcesFile as unknown as SourcesFile);
  if (problems.length) throw new Error("source configuration is invalid: " + problems.join("; "));
  const catalogue = JSON.parse(await readFile(resolve(REPOSITORY_ROOT, "catalogue/sources.json"), "utf-8")) as { product_id: string; title: string; publisher: string; record_count: number }[];
  const products = productCoverage(file, catalogue).map((p) => {
    const states = p.refresh.map((r) => r.state);
    const refresh: RefreshKind = states.includes("working") ? "scheduled" : states.includes("working_cli_only") ? "operator_run"
      : states.includes("exercised_not_run_in_full") ? "exercised_only" : states.includes("disabled_pending_person") ? "pending_decision" : "none";
    return {
      product_id: p.product_id, title: p.title, publisher: catalogue.find((c) => c.product_id === p.product_id)!.publisher,
      catalogue_record_count: p.catalogue_record_count,
      backfill_source_ids: p.backfill.map((r) => r.source_id),
      refresh_source_ids: p.refresh.filter((r) => RUNNABLE.has(r.state)).map((r) => r.source_id),
      refresh, refresh_gap: p.refresh_gap,
    };
  });
  return JSON.stringify({ note: "Generated by ingest/src/loaders/coverage_build.ts. Routes that exist, not rows that are loaded: the explorer reads what the store holds from the database.", products, not_published_for_2026: UNPUBLISHED_2026 }, null, 2) + "\n";
}

if (process.argv[1] && resolve(process.argv[1]) === new URL(import.meta.url).pathname) {
  const text = await buildCoverageFile();
  if (process.argv.includes("--write")) {
    await writeFile(TARGET, text);
    console.log("coverage statement written");
  } else if (text !== (await readFile(TARGET, "utf-8").catch(() => ""))) {
    console.error("web/src/lib/release-coverage.json is out of date: run `node src/loaders/coverage_build.ts --write`");
    process.exit(1);
  } else console.log("coverage statement is up to date");
}
